<font size="+5">#01 | Data Tables & Basic Concepts of Programming</font>

- Subscribe to my [Blog â†—](https://blog.pythonassembly.com/)
- Let's keep in touch on [LinkedIn â†—](www.linkedin.com/in/jsulopz) ðŸ˜„

# Discipline to Search Solutions in Google

> Apply the following steps when **looking for solutions in Google**:
>
> 1. **Necesity**: How to load an Excel in Python?
> 2. **Search in Google**: by keywords
>   - `load excel python`
>   - ~~how to load excel in python~~
> 3. **Solution**: What's the `function()` that loads an Excel in Python?
>   - A Function to Programming is what the Atom to Phisics.
>   - Every time you want to do something in programming
>   - **You will need a `function()`** to make it
>   - Theferore, you must **detect parenthesis `()`**
>   - Out of all the words that you see in a website
>   - Because they indicate the presence of a `function()`.

# Load the Data

In [1]:
import pandas as pd

df = pd.read_excel('df_mortality_regions.xlsx')
df.head()

,Country name,Regional indicator,Population 2020,Population 2019,"COVID-19 deaths per 100,000 population in 2020",Median age,Island,Index of exposure to COVID-19 infections in other countries as of March 31,Log of average distance to SARS countries,WHO Western Pacific Region,Female head of government,Index of institutional trust,Gini coefficient of income,"All-cause death count, 2017","All-cause death count, 2018","All-cause death count, 2019","All-cause death count, 2020","Excess deaths in 2020 per 100,000 population, relative to 2017-2019 average"
0,Finland,Western Europe,5540718.0,5520314.0,10.125000,42.799999,0,2.225083,8.926763,0,1,0.549860,25.9,53546.0,54394.0,53821.0,55663.0,31.510042
1,Denmark,Western Europe,5792203.0,5818553.0,22.409399,42.299999,0,3.953056,9.006084,0,1,0.571761,27.8,53103.0,55076.0,53805.0,55477.0,25.533773
2,Switzerland,Western Europe,8654618.0,8574832.0,88.334305,43.099998,0,5.583522,9.078127,0,0,0.660001,30.1,66703.0,66888.0,67515.0,77087.0,116.680031
3,Iceland,Western Europe,341250.0,361313.0,8.498200,37.299999,1,1.649335,9.069892,0,1,0.325369,24.1,2229.0,2247.0,2261.0,2321.0,21.445267
4,Netherlands,Western Europe,17134873.0,17332850.0,67.260498,43.200001,0,5.573827,9.059903,0,0,0.522208,27.0,149805.0,152991.0,151547.0,171175.0,114.468414

# Islands

## Number of Islands

20

## Which region had more Islands?

### Filter for Islands

,Country name,Regional indicator,Population 2020,Population 2019,"COVID-19 deaths per 100,000 population in 2020",Median age,Island,Index of exposure to COVID-19 infections in other countries as of March 31,Log of average distance to SARS countries,WHO Western Pacific Region,Female head of government,Index of institutional trust,Gini coefficient of income,"All-cause death count, 2017","All-cause death count, 2018","All-cause death count, 2019","All-cause death count, 2020","Excess deaths in 2020 per 100,000 population, relative to 2017-2019 average"
3,Iceland,Western Europe,341250.0,361313.0,8.498200,37.299999,1,1.649335,9.069892,0,1,0.325369,24.100000,2229.0,2247.0,2261.0,2321.0,21.445267
8,New Zealand,North America and ANZ,4822233.0,4917000.0,0.518400,37.900002,1,0.379029,9.266325,1,1,0.526566,34.100000,33495.0,33053.0,34088.0,33177.0,-7.563882
10,Australia,North America and ANZ,25499881.0,25364307.0,3.564700,37.900002,1,0.405097,9.101802,1,0,0.335050,33.000000,NaN,NaN,NaN,NaN,NaN
14,Ireland,Western Europe,4937796.0,4941444.0,45.303600,38.700001,1,3.188102,9.100494,0,0,0.430625,30.600000,NaN,30621.0,30728.0,32271.0,32.320301
16,United Kingdom,Western Europe,67886004.0,66834405.0,108.449501,40.799999,1,5.009473,9.087469,0,0,0.267582,34.070000,606874.0,613309.0,600532.0,696705.0,133.313141
21,Bahrain,Middle East and North Africa,1701583.0,1641172.0,20.686600,32.400002,1,1.666596,8.852241,0,0,0.486931,59.600000,NaN,NaN,NaN,NaN,NaN
22,Malta,Western Europe,441539.0,502653.0,49.599201,42.400002,1,2.822389,9.096670,0,0,0.402808,28.700000,3556.0,3672.0,3684.0,4093.0,96.519936
31,Singapore,Southeast Asia,5850343.0,5703569.0,0.495700,42.400002,1,1.260240,8.425980,1,1,0.868589,45.200000,20905.0,21282.0,21446.0,22000.0,13.657712
36,Jamaica,Latin America and Caribbean,2961161.0,2948279.0,10.198700,31.400000,1,1.044930,9.502089,0,0,0.133247,37.480000,NaN,NaN,NaN,NaN,NaN
38,Cyprus,Western Europe,875899.0,1198575.0,13.586000,37.299999,1,1.907791,8.967679,0,0,0.174157,29.100000,6009.0,5798.0,6218.0,6636.0,60.513317
49,Mauritius,Sub-Saharan Africa,1271767.0,1265711.0,0.786300,37.400002,1,0.624421,9.083909,0,0,0.410803,38.470000,10140.0,10787.0,11174.0,11060.0,28.348383
55,Japan,East Asia,126476458.0,126264931.0,2.602900,48.200001,1,0.862789,8.390191,1,0,0.317466,33.900000,1340567.0,1362470.0,1387775.0,1376426.0,10.146339
60,Philippines,Southeast Asia,109581085.0,108116615.0,8.435801,25.200001,1,0.739615,8.226012,1,0,0.519951,42.230000,NaN,NaN,NaN,NaN,NaN
72,Dominican Republic,Latin America and Caribbean,10847904.0,10738958.0,22.253101,27.600000,1,1.129565,9.502855,0,0,0.198578,44.400000,NaN,NaN,NaN,NaN,NaN
81,Indonesia,Southeast Asia,273523621.0,270625568.0,8.093599,29.299999,1,0.575605,8.577746,0,0,0.560791,37.477500,NaN,NaN,NaN,NaN,NaN
88,Maldives,South Asia,540542.0,530953.0,8.880000,30.600000,1,0.712094,8.737941,0,0,0.327487,37.342500,NaN,NaN,NaN,NaN,NaN
128,Sri Lanka,South Asia,21413250.0,21670000.0,0.952700,34.099998,1,0.704990,8.635092,0,0,0.367545,41.936667,NaN,NaN,NaN,NaN,NaN
129,Comoros,Sub-Saharan Africa,869595.0,850886.0,1.150000,20.400000,1,0.662754,9.128011,0,0,0.138619,45.330000,NaN,NaN,NaN,NaN,NaN
133,Madagascar,Sub-Saharan Africa,27691019.0,26969307.0,0.942500,19.600000,1,0.603193,9.141644,0,0,0.311765,42.650000,NaN,NaN,NaN,NaN,NaN
141,Haiti,Latin America and Caribbean,11402533.0,11263077.0,2.069700,24.299999,1,1.078711,9.501391,0,0,0.216442,50.945000,NaN,NaN,NaN,NaN,NaN

### Count number of `Islands` in each `Region`

Western Europe                  5
Southeast Asia                  3
Latin America and Caribbean     3
Sub-Saharan Africa              3
North America and ANZ           2
South Asia                      2
Middle East and North Africa    1
East Asia                       1
Name: Regional indicator, dtype: int64

### Pick the one with most Islands

In [8]:
df[mask]['Regional indicator'].value_counts()[:1]

Western Europe    5
Name: Regional indicator, dtype: int64

## Show all Columns for these Islands

,Country name,Regional indicator,Population 2020,Population 2019,"COVID-19 deaths per 100,000 population in 2020",Median age,Island,Index of exposure to COVID-19 infections in other countries as of March 31,Log of average distance to SARS countries,WHO Western Pacific Region,Female head of government,Index of institutional trust,Gini coefficient of income,"All-cause death count, 2017","All-cause death count, 2018","All-cause death count, 2019","All-cause death count, 2020","Excess deaths in 2020 per 100,000 population, relative to 2017-2019 average"
3,Iceland,Western Europe,341250.0,361313.0,8.498200,37.299999,1,1.649335,9.069892,0,1,0.325369,24.10,2229.0,2247.0,2261.0,2321.0,21.445267
14,Ireland,Western Europe,4937796.0,4941444.0,45.303600,38.700001,1,3.188102,9.100494,0,0,0.430625,30.60,NaN,30621.0,30728.0,32271.0,32.320301
16,United Kingdom,Western Europe,67886004.0,66834405.0,108.449501,40.799999,1,5.009473,9.087469,0,0,0.267582,34.07,606874.0,613309.0,600532.0,696705.0,133.313141
22,Malta,Western Europe,441539.0,502653.0,49.599201,42.400002,1,2.822389,9.096670,0,0,0.402808,28.70,3556.0,3672.0,3684.0,4093.0,96.519936
38,Cyprus,Western Europe,875899.0,1198575.0,13.586000,37.299999,1,1.907791,8.967679,0,0,0.174157,29.10,6009.0,5798.0,6218.0,6636.0,60.513317

## Mean Age of across the above Islands?

39.3

# Female Heads of State

## Number of Countries with Female Heads of State

22

## Which region had more Female Heads of State?

### Filter for Countries with Female Heads of State

,Country name,Regional indicator,Population 2020,Population 2019,"COVID-19 deaths per 100,000 population in 2020",Median age,Island,Index of exposure to COVID-19 infections in other countries as of March 31,Log of average distance to SARS countries,WHO Western Pacific Region,Female head of government,Index of institutional trust,Gini coefficient of income,"All-cause death count, 2017","All-cause death count, 2018","All-cause death count, 2019","All-cause death count, 2020","Excess deaths in 2020 per 100,000 population, relative to 2017-2019 average"
0,Finland,Western Europe,5540718.0,5520314.0,10.125000,42.799999,0,2.225083,8.926763,0,1,0.549860,25.900000,53546.0,54394.0,53821.0,55663.0,31.510042
1,Denmark,Western Europe,5792203.0,5818553.0,22.409399,42.299999,0,3.953056,9.006084,0,1,0.571761,27.800000,53103.0,55076.0,53805.0,55477.0,25.533773
3,Iceland,Western Europe,341250.0,361313.0,8.498200,37.299999,1,1.649335,9.069892,0,1,0.325369,24.100000,2229.0,2247.0,2261.0,2321.0,21.445267
5,Norway,Western Europe,5421242.0,5347896.0,8.042400,39.700001,0,2.675678,8.993008,0,1,0.605656,24.800000,40634.0,40716.0,40500.0,41155.0,9.997681
8,New Zealand,North America and ANZ,4822233.0,4917000.0,0.518400,37.900002,1,0.379029,9.266325,1,1,0.526566,34.100000,33495.0,33053.0,34088.0,33177.0,-7.563882
12,Germany,Western Europe,83783945.0,83132799.0,40.331100,46.599998,0,4.837829,9.017697,0,1,0.435435,31.100000,929351.0,952295.0,936772.0,1000855.0,73.548416
23,Taiwan Province of China,East Asia,23816775.0,23780000.0,0.029400,42.200001,0,0.888295,8.087669,1,1,0.157968,29.466667,171242.0,172784.0,176296.0,173156.0,-1.196181
31,Singapore,Southeast Asia,5850343.0,5703569.0,0.495700,42.400002,1,1.260240,8.425980,1,1,0.868589,45.200000,20905.0,21282.0,21446.0,22000.0,13.657712
32,Kosovo,Central and Eastern Europe,1932774.0,1794248.0,68.916496,35.000000,0,3.134411,9.014949,0,1,0.169448,29.010000,8738.0,8866.0,9552.0,11108.0,110.329376
33,Slovakia,Central and Eastern Europe,5459643.0,5454073.0,39.160103,41.200001,0,4.655188,9.018951,0,1,0.195352,23.200000,53702.0,54137.0,53115.0,60277.0,121.419106
37,Lithuania,Central and Eastern Europe,2722291.0,2786844.0,53.557800,43.500000,0,2.538997,8.944459,0,1,0.189153,36.900000,39990.0,39452.0,38184.0,43824.0,167.551971
39,Estonia,Central and Eastern Europe,1326539.0,1326590.0,17.263000,42.700001,0,2.365309,8.930442,0,1,0.270277,30.600000,15476.0,15684.0,15332.0,16206.0,53.421223
47,Serbia,Central and Eastern Europe,6804596.0,6944975.0,47.188698,41.200001,0,3.134411,9.014949,0,1,0.220901,37.800000,103722.0,101655.0,102131.0,114954.0,181.115997
67,Greece,Western Europe,10423056.0,10716322.0,46.416298,45.299999,0,2.327332,9.025694,0,1,0.124216,32.300000,124069.0,119952.0,124538.0,132966.0,95.679260
86,Nepal,South Asia,29136808.0,28608710.0,6.369900,25.000000,0,0.877291,8.417630,0,1,0.392217,32.840000,NaN,NaN,NaN,NaN,NaN
100,Bangladesh,South Asia,164689383.0,163046161.0,4.589900,27.500000,0,0.823931,8.348938,0,1,0.576998,43.972500,NaN,NaN,NaN,NaN,NaN
107,Georgia,Commonwealth of Independent States,3989175.0,3720382.0,62.794899,38.700001,0,1.705543,8.850701,0,1,0.198271,37.940000,NaN,NaN,NaN,NaN,NaN
111,Gabon,Sub-Saharan Africa,2225728.0,2172579.0,2.875500,23.100000,0,0.864660,9.304911,0,1,0.103891,38.020000,NaN,NaN,NaN,NaN,NaN
123,Namibia,Sub-Saharan Africa,2540916.0,2494530.0,8.068000,22.000000,0,0.625211,9.349452,0,1,0.310684,57.535000,NaN,NaN,NaN,NaN,NaN
125,Myanmar,Southeast Asia,54409794.0,54045420.0,4.929300,29.100000,0,0.759283,8.298598,0,1,0.621468,38.070000,NaN,NaN,NaN,NaN,NaN
131,Ethiopia,Sub-Saharan Africa,114963583.0,112078730.0,1.672700,19.799999,0,0.915070,9.047482,0,1,0.396865,33.497500,NaN,NaN,NaN,NaN,NaN
134,Togo,Sub-Saharan Africa,8278737.0,8082366.0,0.821400,19.400000,0,0.966354,9.329301,0,1,0.212306,43.060000,NaN,NaN,NaN,NaN,NaN

### Count number of `Islands` in each `Region`

Western Europe                        6
Central and Eastern Europe            5
Sub-Saharan Africa                    4
Southeast Asia                        2
South Asia                            2
North America and ANZ                 1
East Asia                             1
Commonwealth of Independent States    1
Name: Regional indicator, dtype: int64

### Pick the one with most Islands

In [27]:
res[:1]

Western Europe    6
Name: Regional indicator, dtype: int64

## Show all Columns for these Countries

,Country name,Regional indicator,Population 2020,Population 2019,"COVID-19 deaths per 100,000 population in 2020",Median age,Island,Index of exposure to COVID-19 infections in other countries as of March 31,Log of average distance to SARS countries,WHO Western Pacific Region,Female head of government,Index of institutional trust,Gini coefficient of income,"All-cause death count, 2017","All-cause death count, 2018","All-cause death count, 2019","All-cause death count, 2020","Excess deaths in 2020 per 100,000 population, relative to 2017-2019 average"
0,Finland,Western Europe,5540718.0,5520314.0,10.125000,42.799999,0,2.225083,8.926763,0,1,0.549860,25.9,53546.0,54394.0,53821.0,55663.0,31.510042
1,Denmark,Western Europe,5792203.0,5818553.0,22.409399,42.299999,0,3.953056,9.006084,0,1,0.571761,27.8,53103.0,55076.0,53805.0,55477.0,25.533773
3,Iceland,Western Europe,341250.0,361313.0,8.498200,37.299999,1,1.649335,9.069892,0,1,0.325369,24.1,2229.0,2247.0,2261.0,2321.0,21.445267
5,Norway,Western Europe,5421242.0,5347896.0,8.042400,39.700001,0,2.675678,8.993008,0,1,0.605656,24.8,40634.0,40716.0,40500.0,41155.0,9.997681
12,Germany,Western Europe,83783945.0,83132799.0,40.331100,46.599998,0,4.837829,9.017697,0,1,0.435435,31.1,929351.0,952295.0,936772.0,1000855.0,73.548416
67,Greece,Western Europe,10423056.0,10716322.0,46.416298,45.299999,0,2.327332,9.025694,0,1,0.124216,32.3,124069.0,119952.0,124538.0,132966.0,95.679260

## Mean Age of across the above Countries?

42.33333269755045

## Show All Columns for the Country with more deaths due to Covid per 100,000 people

Country name                                                                          Belgium
Regional indicator                                                             Western Europe
Population 2020                                                                    11589616.0
Population 2019                                                                    11484055.0
COVID-19 deaths per 100,000 population in 2020                                     168.495697
Median age                                                                          41.799999
Island                                                                                      0
Index of exposure to COVID-19  infections in other countries as of March 31          6.343308
Log of average distance to SARS countries                                            9.071179
WHO Western Pacific Region                                                                  0
Female head of government                                                                   0
Index of institutional trust                                                         0.302762
Gini coefficient of income                                                               25.6
All-cause death count, 2017                                                          109278.0
All-cause death count, 2018                                                          110341.0
All-cause death count, 2019                                                          108436.0
All-cause death count, 2020                                                          128952.0
Excess deaths in 2020 per 100,000 population, relative to 2017-2019 average        169.893524
Name: 19, dtype: object

# Achieved Goals

_Double click on **this cell** and place an `X` inside the square brackets (i.e., [X]) if you think you understand the goal:_

- [ ] Identify the **Elements of Programming** thanks to the syntax.
- [ ] Use `functions` that belongs to external `libraries`.
- [ ] Get _the machine to work for you, not against you_.
  - [ ] `shift + tab` to ask help to Python.
  - [ ] `tab` to ask Python for suggestions.
- [ ] Understand that a `dog` doesn't make `miau()`. But, rather `guau()`... the same way a `DataFrame` cannot `fly()` (i.e., `DataFrame.fly()`?).
- [ ] All roads lead to Rome; We can achieve the **the same result with different lines of code**.
  - We reproduced a scatterplot using 3 different lines of code.